//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Cosmos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Starship", Namespace="http://schemas.datacontract.org/2004/07/SpaceYDTO")]
    [System.SerializableAttribute()]
    public partial class Starship : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.Cosmos.Person[] CrewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GoldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShipPowerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.Cosmos.Person[] Crew {
            get {
                return this.CrewField;
            }
            set {
                if ((object.ReferenceEquals(this.CrewField, value) != true)) {
                    this.CrewField = value;
                    this.RaisePropertyChanged("Crew");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Gold {
            get {
                return this.GoldField;
            }
            set {
                if ((this.GoldField.Equals(value) != true)) {
                    this.GoldField = value;
                    this.RaisePropertyChanged("Gold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShipPower {
            get {
                return this.ShipPowerField;
            }
            set {
                if ((this.ShipPowerField.Equals(value) != true)) {
                    this.ShipPowerField = value;
                    this.RaisePropertyChanged("ShipPower");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/SpaceYDTO")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NickField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nick {
            get {
                return this.NickField;
            }
            set {
                if ((object.ReferenceEquals(this.NickField, value) != true)) {
                    this.NickField = value;
                    this.RaisePropertyChanged("Nick");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpaceSystem", Namespace="http://schemas.datacontract.org/2004/07/SpaceYDTO")]
    [System.SerializableAttribute()]
    public partial class SpaceSystem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BaseDistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BaseDistance {
            get {
                return this.BaseDistanceField;
            }
            set {
                if ((this.BaseDistanceField.Equals(value) != true)) {
                    this.BaseDistanceField = value;
                    this.RaisePropertyChanged("BaseDistance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Cosmos.ICosmosService")]
    public interface ICosmosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICosmosService/InitializeGame", ReplyAction="http://tempuri.org/ICosmosService/InitializeGameResponse")]
        void InitializeGame();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICosmosService/InitializeGame", ReplyAction="http://tempuri.org/ICosmosService/InitializeGameResponse")]
        System.Threading.Tasks.Task InitializeGameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICosmosService/SendStarship", ReplyAction="http://tempuri.org/ICosmosService/SendStarshipResponse")]
        Client.Cosmos.Starship SendStarship(Client.Cosmos.Starship starship, string systemName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICosmosService/SendStarship", ReplyAction="http://tempuri.org/ICosmosService/SendStarshipResponse")]
        System.Threading.Tasks.Task<Client.Cosmos.Starship> SendStarshipAsync(Client.Cosmos.Starship starship, string systemName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICosmosService/GetSystem", ReplyAction="http://tempuri.org/ICosmosService/GetSystemResponse")]
        Client.Cosmos.SpaceSystem GetSystem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICosmosService/GetSystem", ReplyAction="http://tempuri.org/ICosmosService/GetSystemResponse")]
        System.Threading.Tasks.Task<Client.Cosmos.SpaceSystem> GetSystemAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICosmosService/GetStarship", ReplyAction="http://tempuri.org/ICosmosService/GetStarshipResponse")]
        Client.Cosmos.Starship GetStarship(int money);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICosmosService/GetStarship", ReplyAction="http://tempuri.org/ICosmosService/GetStarshipResponse")]
        System.Threading.Tasks.Task<Client.Cosmos.Starship> GetStarshipAsync(int money);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICosmosServiceChannel : Client.Cosmos.ICosmosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CosmosServiceClient : System.ServiceModel.ClientBase<Client.Cosmos.ICosmosService>, Client.Cosmos.ICosmosService {
        
        public CosmosServiceClient() {
        }
        
        public CosmosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CosmosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CosmosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CosmosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InitializeGame() {
            base.Channel.InitializeGame();
        }
        
        public System.Threading.Tasks.Task InitializeGameAsync() {
            return base.Channel.InitializeGameAsync();
        }
        
        public Client.Cosmos.Starship SendStarship(Client.Cosmos.Starship starship, string systemName) {
            return base.Channel.SendStarship(starship, systemName);
        }
        
        public System.Threading.Tasks.Task<Client.Cosmos.Starship> SendStarshipAsync(Client.Cosmos.Starship starship, string systemName) {
            return base.Channel.SendStarshipAsync(starship, systemName);
        }
        
        public Client.Cosmos.SpaceSystem GetSystem() {
            return base.Channel.GetSystem();
        }
        
        public System.Threading.Tasks.Task<Client.Cosmos.SpaceSystem> GetSystemAsync() {
            return base.Channel.GetSystemAsync();
        }
        
        public Client.Cosmos.Starship GetStarship(int money) {
            return base.Channel.GetStarship(money);
        }
        
        public System.Threading.Tasks.Task<Client.Cosmos.Starship> GetStarshipAsync(int money) {
            return base.Channel.GetStarshipAsync(money);
        }
    }
}
