//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client2.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/Models")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Review", Namespace="http://schemas.datacontract.org/2004/07/Models")]
    [System.SerializableAttribute()]
    public partial class Review : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client2.ServiceReference2.Person AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MovieIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client2.ServiceReference2.Person Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MovieId {
            get {
                return this.MovieIdField;
            }
            set {
                if ((this.MovieIdField.Equals(value) != true)) {
                    this.MovieIdField = value;
                    this.RaisePropertyChanged("MovieId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IReviewAndPersonWCFService")]
    public interface IReviewAndPersonWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewAndPersonWCFService/GetAllPeople", ReplyAction="http://tempuri.org/IReviewAndPersonWCFService/GetAllPeopleResponse")]
        Client2.ServiceReference2.Person[] GetAllPeople();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewAndPersonWCFService/GetAllPeople", ReplyAction="http://tempuri.org/IReviewAndPersonWCFService/GetAllPeopleResponse")]
        System.Threading.Tasks.Task<Client2.ServiceReference2.Person[]> GetAllPeopleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewAndPersonWCFService/AddPerson", ReplyAction="http://tempuri.org/IReviewAndPersonWCFService/AddPersonResponse")]
        int AddPerson(Client2.ServiceReference2.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewAndPersonWCFService/AddPerson", ReplyAction="http://tempuri.org/IReviewAndPersonWCFService/AddPersonResponse")]
        System.Threading.Tasks.Task<int> AddPersonAsync(Client2.ServiceReference2.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewAndPersonWCFService/GetPerson", ReplyAction="http://tempuri.org/IReviewAndPersonWCFService/GetPersonResponse")]
        Client2.ServiceReference2.Person GetPerson(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewAndPersonWCFService/GetPerson", ReplyAction="http://tempuri.org/IReviewAndPersonWCFService/GetPersonResponse")]
        System.Threading.Tasks.Task<Client2.ServiceReference2.Person> GetPersonAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewAndPersonWCFService/UpdatePerson", ReplyAction="http://tempuri.org/IReviewAndPersonWCFService/UpdatePersonResponse")]
        Client2.ServiceReference2.Person UpdatePerson(Client2.ServiceReference2.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewAndPersonWCFService/UpdatePerson", ReplyAction="http://tempuri.org/IReviewAndPersonWCFService/UpdatePersonResponse")]
        System.Threading.Tasks.Task<Client2.ServiceReference2.Person> UpdatePersonAsync(Client2.ServiceReference2.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewAndPersonWCFService/GetAllReviews", ReplyAction="http://tempuri.org/IReviewAndPersonWCFService/GetAllReviewsResponse")]
        Client2.ServiceReference2.Review[] GetAllReviews();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewAndPersonWCFService/GetAllReviews", ReplyAction="http://tempuri.org/IReviewAndPersonWCFService/GetAllReviewsResponse")]
        System.Threading.Tasks.Task<Client2.ServiceReference2.Review[]> GetAllReviewsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewAndPersonWCFService/AddReview", ReplyAction="http://tempuri.org/IReviewAndPersonWCFService/AddReviewResponse")]
        int AddReview(Client2.ServiceReference2.Review review);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewAndPersonWCFService/AddReview", ReplyAction="http://tempuri.org/IReviewAndPersonWCFService/AddReviewResponse")]
        System.Threading.Tasks.Task<int> AddReviewAsync(Client2.ServiceReference2.Review review);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewAndPersonWCFService/GetReview", ReplyAction="http://tempuri.org/IReviewAndPersonWCFService/GetReviewResponse")]
        Client2.ServiceReference2.Review GetReview(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewAndPersonWCFService/GetReview", ReplyAction="http://tempuri.org/IReviewAndPersonWCFService/GetReviewResponse")]
        System.Threading.Tasks.Task<Client2.ServiceReference2.Review> GetReviewAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewAndPersonWCFService/UpdateReview", ReplyAction="http://tempuri.org/IReviewAndPersonWCFService/UpdateReviewResponse")]
        Client2.ServiceReference2.Review UpdateReview(Client2.ServiceReference2.Review review);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReviewAndPersonWCFService/UpdateReview", ReplyAction="http://tempuri.org/IReviewAndPersonWCFService/UpdateReviewResponse")]
        System.Threading.Tasks.Task<Client2.ServiceReference2.Review> UpdateReviewAsync(Client2.ServiceReference2.Review review);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReviewAndPersonWCFServiceChannel : Client2.ServiceReference2.IReviewAndPersonWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReviewAndPersonWCFServiceClient : System.ServiceModel.ClientBase<Client2.ServiceReference2.IReviewAndPersonWCFService>, Client2.ServiceReference2.IReviewAndPersonWCFService {
        
        public ReviewAndPersonWCFServiceClient() {
        }
        
        public ReviewAndPersonWCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReviewAndPersonWCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReviewAndPersonWCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReviewAndPersonWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client2.ServiceReference2.Person[] GetAllPeople() {
            return base.Channel.GetAllPeople();
        }
        
        public System.Threading.Tasks.Task<Client2.ServiceReference2.Person[]> GetAllPeopleAsync() {
            return base.Channel.GetAllPeopleAsync();
        }
        
        public int AddPerson(Client2.ServiceReference2.Person person) {
            return base.Channel.AddPerson(person);
        }
        
        public System.Threading.Tasks.Task<int> AddPersonAsync(Client2.ServiceReference2.Person person) {
            return base.Channel.AddPersonAsync(person);
        }
        
        public Client2.ServiceReference2.Person GetPerson(int id) {
            return base.Channel.GetPerson(id);
        }
        
        public System.Threading.Tasks.Task<Client2.ServiceReference2.Person> GetPersonAsync(int id) {
            return base.Channel.GetPersonAsync(id);
        }
        
        public Client2.ServiceReference2.Person UpdatePerson(Client2.ServiceReference2.Person person) {
            return base.Channel.UpdatePerson(person);
        }
        
        public System.Threading.Tasks.Task<Client2.ServiceReference2.Person> UpdatePersonAsync(Client2.ServiceReference2.Person person) {
            return base.Channel.UpdatePersonAsync(person);
        }
        
        public Client2.ServiceReference2.Review[] GetAllReviews() {
            return base.Channel.GetAllReviews();
        }
        
        public System.Threading.Tasks.Task<Client2.ServiceReference2.Review[]> GetAllReviewsAsync() {
            return base.Channel.GetAllReviewsAsync();
        }
        
        public int AddReview(Client2.ServiceReference2.Review review) {
            return base.Channel.AddReview(review);
        }
        
        public System.Threading.Tasks.Task<int> AddReviewAsync(Client2.ServiceReference2.Review review) {
            return base.Channel.AddReviewAsync(review);
        }
        
        public Client2.ServiceReference2.Review GetReview(int id) {
            return base.Channel.GetReview(id);
        }
        
        public System.Threading.Tasks.Task<Client2.ServiceReference2.Review> GetReviewAsync(int id) {
            return base.Channel.GetReviewAsync(id);
        }
        
        public Client2.ServiceReference2.Review UpdateReview(Client2.ServiceReference2.Review review) {
            return base.Channel.UpdateReview(review);
        }
        
        public System.Threading.Tasks.Task<Client2.ServiceReference2.Review> UpdateReviewAsync(Client2.ServiceReference2.Review review) {
            return base.Channel.UpdateReviewAsync(review);
        }
    }
}
